# Generated by Django 3.0.2 on 2020-02-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_history_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='operation',
            new_name='operator',
        ),
    ]
