# Generated by Django 3.0.2 on 2020-02-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20200226_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='input1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='input2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='result',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
